<a href="https://colab.research.google.com/github/Devikasatheesh12/Traffic-Light-Classifier/blob/main/CNN_PROJECT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

INTRODUCTION


Traffic light recognition plays a crucial role in modern transportation systems, aiding in the efficient flow of traffic and enhancing road safety. With the advancement of computer vision and deep learning technologies, the development of robust traffic light classifiers has become feasible, offering automated solutions for traffic management and control.

In this project, I aim to implement a Convolutional Neural Network based traffic light classifier. CNNs are a class of deep neural networks specifically designed for analyzing visual data, making them well-suited for tasks like image classification. By leveraging the power of CNNs, we can create a model capable of accurately identifying the state of traffic lights from images captured by cameras or sensors in real-time.

In [ ]:
import pandas as pd
import os
from skimage.io import imread
from skimage.transform import resize
from keras.layers import MaxPool2D,Dense,Conv2D,Flatten
from keras.models import Sequential

In [ ]:
os.listdir("/content/drive/MyDrive/traffic/traffic_light_data/train")

['back', 'green', 'red', 'yellow']

In [ ]:
os.listdir("/content/drive/MyDrive/traffic/traffic_light_data/test")

['green', 'red', 'yellow', 'back']

In [ ]:
X_train=[]
y_train=[]
Categories=['back', 'green', 'red', 'yellow']
datadir="/content/drive/MyDrive/traffic/traffic_light_data/train"
for i in Categories:
  print("Loading......",i)
  path=os.path.join(datadir,i)
  print(path)
  images=os.listdir(path)
  print(images)
  for img in images:
    img_path=os.path.join(path,img)
    img_arr=imread(img_path)
    img_resized=resize(img_arr,(150,150,1))
    X_train.append(img_resized)
    y_train.append(Categories.index(i))
  print("completed....",i)

Loading...... back
/content/drive/MyDrive/traffic/traffic_light_data/train/back
['back_387.png', 'back_391.png', 'back_384.png', 'back_436.png', 'back_429.png', 'back_428.png', 'back_425.png', 'back_420.png', 'back_421.png', 'back_424.png', 'back_422.png', 'back_426.png', 'back_423.png', 'back_427.png', 'back_42.png', 'back_419.png', 'back_414.png', 'back_412.png', 'back_413.png', 'back_417.png', 'back_416.png', 'back_415.png', 'back_411.png', 'back_382.png', 'back_409.png', 'back_40.png', 'back_393.png', 'back_395.png', 'back_396.png', 'back_399.png', 'back_398.png', 'back_4.png', 'back_397.png', 'back_394.png', 'back_390.png', 'back_389.png', 'back_385.png', 'back_392.png', 'back_39.png', 'back_386.png', 'back_388.png', 'back_410.png', 'back_400.png', 'back_403.png', 'back_406.png', 'back_404.png', 'back_407.png', 'back_408.png', 'back_402.png', 'back_405.png', 'back_38.png', 'back_378.png', 'back_376.png', 'back_377.png', 'back_381.png', 'back_379.png', 'back_380.png', 'back_41.png'

In [ ]:
img_arr.shape

(62, 28, 3)

In [ ]:
img_arr

array([[[216, 220, 223],
        [217, 221, 224],
        [214, 219, 222],
        ...,
        [183, 187, 190],
        [175, 176, 180],
        [167, 168, 172]],

       [[221, 225, 228],
        [214, 218, 221],
        [216, 221, 224],
        ...,
        [171, 175, 178],
        [162, 163, 167],
        [154, 155, 159]],

       [[213, 217, 220],
        [217, 221, 224],
        [217, 221, 224],
        ...,
        [159, 160, 164],
        [149, 150, 154],
        [140, 141, 145]],

       ...,

       [[219, 224, 227],
        [218, 223, 226],
        [218, 223, 226],
        ...,
        [225, 226, 228],
        [224, 228, 229],
        [224, 228, 229]],

       [[219, 225, 225],
        [218, 224, 224],
        [219, 224, 227],
        ...,
        [222, 226, 227],
        [220, 224, 225],
        [222, 226, 227]],

       [[219, 225, 225],
        [219, 225, 225],
        [220, 225, 228],
        ...,
        [224, 228, 229],
        [226, 230, 231],
        [220, 224, 225]]], dtype=uint8)

In [ ]:
img_resized.shape

(150, 150, 1)

In [ ]:
img_resized

array([[[0.86538282],
        [0.86636861],
        [0.86735441],
        ...,
        [0.6478139 ],
        [0.6536701 ],
        [0.65952631]],

       [[0.86419554],
        [0.86416626],
        [0.86413698],
        ...,
        [0.6566505 ],
        [0.66250671],
        [0.66836291]],

       [[0.86702674],
        [0.86941803],
        [0.87180931],
        ...,
        [0.6355786 ],
        [0.64143481],
        [0.64729102]],

       ...,

       [[0.87570467],
        [0.87609509],
        [0.8764855 ],
        ...,
        [0.8799421 ],
        [0.88121094],
        [0.88247979]],

       [[0.87636384],
        [0.87645169],
        [0.87653953],
        ...,
        [0.87713251],
        [0.88082192],
        [0.88451133]],

       [[0.87608742],
        [0.87630214],
        [0.87651687],
        ...,
        [0.87831072],
        [0.88098506],
        [0.88365939]]])

In [ ]:
X_test=[]
y_test=[]
Categories=['back', 'green', 'red', 'yellow']
datadir="/content/drive/MyDrive/traffic/traffic_light_data/test"
for i in Categories:
  print("Loading.....",i)
  path=os.path.join(datadir,i)
  print(path)
  images=os.listdir(path)
  for img in images:
    img_path=os.path.join(path,img)
    img_arr=imread(img_path)
    img_resized=resize(img_arr,(150,150,1))
    X_test.append(img_resized)
    y_test.append(Categories.index(i))
  print("completed....",i)

Loading..... back
/content/drive/MyDrive/traffic/traffic_light_data/test/back
completed.... back
completed.... back
completed.... back
completed.... back
completed.... back
completed.... back
completed.... back
completed.... back
completed.... back
completed.... back
completed.... back
completed.... back
completed.... back
completed.... back
completed.... back
completed.... back
completed.... back
completed.... back
completed.... back
completed.... back
completed.... back
completed.... back
completed.... back
completed.... back
completed.... back
completed.... back
completed.... back
completed.... back
completed.... back
completed.... back
completed.... back
completed.... back
completed.... back
completed.... back
completed.... back
completed.... back
completed.... back
completed.... back
completed.... back
completed.... back
completed.... back
completed.... back
completed.... back
completed.... back
completed.... back
completed.... back
completed.... back
completed.... back
completed.

In [ ]:
import numpy as np
X_train=np.array(X_train)
y_train=np.array(y_train)
X_test=np.array(X_test)
y_test=np.array(y_test)

In [ ]:
X_train.shape

(2143, 150, 150, 1)

In [ ]:
y_train.shape

(2143,)

In [ ]:
X_test.shape

(383, 150, 150, 1)

In [ ]:
y_test.shape

(383,)

In [ ]:
model=Sequential()
model.add(Conv2D(32,(3,3),input_shape=(150,150,1),activation='relu'))
model.add(MaxPool2D(2,2))
model.add(Conv2D(32,(3,3),activation='relu'))
model.add(MaxPool2D(2,2))
model.add(Conv2D(64,(3,3),activation='relu'))
model.add(MaxPool2D(2,2))
model.add(Conv2D(64,(3,3),activation='relu'))
model.add(MaxPool2D(2,2))
model.add(Conv2D(128,(3,3),activation='relu'))
model.add(MaxPool2D(2,2))
model.add(Flatten())
model.add(Dense(100,activation='relu'))
model.add(Dense(4,activation='softmax'))

In [ ]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [ ]:
model.fit(X_train,y_train,epochs=20,batch_size=20)

Epoch 1/20
108/108 [==============================] - 3s 16ms/step - loss: 0.4401 - accuracy: 0.8404
Epoch 2/20
108/108 [==============================] - 2s 16ms/step - loss: 0.1209 - accuracy: 0.9673
Epoch 3/20
108/108 [==============================] - 1s 12ms/step - loss: 0.1134 - accuracy: 0.9715
Epoch 4/20
108/108 [==============================] - 1s 11ms/step - loss: 0.0906 - accuracy: 0.9757
Epoch 5/20
108/108 [==============================] - 1s 12ms/step - loss: 0.0535 - accuracy: 0.9888
Epoch 6/20
108/108 [==============================] - 1s 12ms/step - loss: 0.0626 - accuracy: 0.9855
Epoch 7/20
108/108 [==============================] - 1s 12ms/step - loss: 0.0509 - accuracy: 0.9869
Epoch 8/20
108/108 [==============================] - 1s 11ms/step - loss: 0.0435 - accuracy: 0.9855
Epoch 9/20
108/108 [==============================] - 1s 11ms/step - loss: 0.0193 - accuracy: 0.9953
Epoch 10/20
108/108 [==============================] - 1s 11ms/step - loss: 0.0441 - accura

In [ ]:
model.save("model2.h5")

In [ ]:
model.evaluate(X_test,y_test)

12/12 [==============================] - 1s 36ms/step - loss: 0.5679 - accuracy: 0.9138


[0.5679229497909546, 0.9138381481170654]

In [ ]:
img=imread("/content/drive/MyDrive/traffic/traffic_light_data/test/red/red_1.png")
img

array([[[183, 181, 179, 255],
        [187, 182, 180, 255],
        [220, 217, 208, 255],
        [229, 227, 216, 255],
        [228, 226, 216, 255],
        [228, 226, 216, 255]],

       [[177, 176, 175, 255],
        [175, 172, 170, 255],
        [215, 209, 202, 255],
        [229, 226, 215, 255],
        [228, 226, 215, 255],
        [228, 226, 215, 255]],

       [[171, 167, 168, 255],
        [191, 163, 160, 255],
        [220, 189, 173, 255],
        [226, 211, 194, 255],
        [220, 217, 205, 255],
        [223, 220, 208, 255]],

       [[209, 153, 150, 255],
        [247, 159, 139, 255],
        [255, 167, 120, 255],
        [250, 184, 153, 255],
        [223, 199, 184, 255],
        [210, 208, 194, 255]],

       [[255, 150, 126, 255],
        [255, 173, 115, 255],
        [255, 174, 115, 255],
        [255, 176, 120, 255],
        [255, 182, 148, 255],
        [222, 209, 195, 255]],

       [[255, 170, 109, 255],
        [255, 175, 117, 255],
        [255, 174, 110, 255],


In [ ]:
img=resize(img,(150,150,1))
img.shape

(150, 150, 1)

In [ ]:
img=img.reshape(1,150,150,1)
img.shape

(1, 150, 150, 1)

In [ ]:
pred=model.predict(img)
pred

1/1 [==============================] - 0s 387ms/step


array([[1.0015935e-09, 8.6866856e-07, 9.9999845e-01, 7.5158152e-07]],
      dtype=float32)

In [ ]:
ind=pred.argmax(axis=1)
ind

array([2])

In [ ]:
Categories[ind.item()]

'red'